#user input
name = input("Enter your Name")
print(name)
print(type(name))
num = input("Enter Roll Number")
print(num)
print(type(num))
num = int(input("Enter Roll Number"))
print(num)
print(type(num))
